# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.5.0"

package:
  name: wire-memory
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/wire-memory/wire_memory-${{ version }}.tar.gz
    sha256: 9662ed54f52180f865f31cdfd1a48c14fa16aeb79acb92c23e3c23c0886c39c5

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - wiredb >=0.4.0,<0.5.0

tests:
  - python:
      imports: wire_memory
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/davidbrochart/wiredb
  summary: Wire for communicating over memory.

extra:
  recipe-maintainers:
    - davidbrochart
